[package]
name = "mosaic-stm"
version = "0.1.0"
authors = ["Mark Winterrowd <markwinterrowd4@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
indexmap = "1.3.0"
lazy_static = "1.4.0"
crossbeam-epoch = "0.8"

[dev-dependencies]
threadpool = "1.7.1"
rand = "0.7.3"
